language: node_js
sudo: false
node_js:
- node
branches:
  only:
    - master
    - /v\d+\.\d+\.\d+/
before_install: 
- yarn global add greenkeeper-lockfile@1
install:
- npm install
before_script:
- greenkeeper-lockfile-update
after_script: 
- greenkeeper-lockfile-upload
deploy:
  skip_cleanup: true
  provider: npm
  email: adam@kreczko-lenner.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    branch: master
    repo: adamkl/graphql-xsd
